"""create review lifecycle tables

Revision ID: 5732b452c03b
Revises: 
Create Date: 2026-09-28 15:52:42.652869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5732b452c03b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=True)
    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author_login', sa.String(length=100), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=False),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_pr_number', name='uq_repo_pr_number')
    )
    op.create_index(op.f('ix_pull_requests_github_pr_number'), 'pull_requests', ['github_pr_number'], unique=False)
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_table('review_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pull_request_id', sa.String(length=36), nullable=False),
    sa.Column('delivery_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('memory_recalled_count', sa.Integer(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message_safe', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_runs_delivery_id'), 'review_runs', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_review_runs_pull_request_id'), 'review_runs', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_review_runs_status'), 'review_runs', ['status'], unique=False)
    op.create_table('memory_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_run_id', sa.String(length=36), nullable=False),
    sa.Column('memory_source_id', sa.String(length=100), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=True),
    sa.Column('memory_text_sanitized', sa.Text(), nullable=False),
    sa.Column('relevance_context', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('rank_order', sa.Integer(), nullable=False),
    sa.Column('recall_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_audits_review_run_id'), 'memory_audits', ['review_run_id'], unique=False)
    op.create_table('review_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_run_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('published_comment_id', sa.String(length=100), nullable=True),
    sa.Column('feedback_status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_findings_review_run_id'), 'review_findings', ['review_run_id'], unique=False)
    op.create_index(op.f('ix_review_findings_severity'), 'review_findings', ['severity'], unique=False)
    op.create_table('review_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_run_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('actor_login', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['review_findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_feedback_finding_id'), 'review_feedback', ['finding_id'], unique=False)
    op.create_index(op.f('ix_review_feedback_review_run_id'), 'review_feedback', ['review_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_feedback_review_run_id'), table_name='review_feedback')
    op.drop_index(op.f('ix_review_feedback_finding_id'), table_name='review_feedback')
    op.drop_table('review_feedback')
    op.drop_index(op.f('ix_review_findings_severity'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_review_run_id'), table_name='review_findings')
    op.drop_table('review_findings')
    op.drop_index(op.f('ix_memory_audits_review_run_id'), table_name='memory_audits')
    op.drop_table('memory_audits')
    op.drop_index(op.f('ix_review_runs_status'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_pull_request_id'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_delivery_id'), table_name='review_runs')
    op.drop_table('review_runs')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_github_pr_number'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
